name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: 'Upload Artifact'
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: build/reports
        retention-days: 5
